### ISSUE TITLE
Use bin stubs?

### ISSUE THREAD

**Issue by nathancolgate** [brandnewbox/bnb-dip-defaults#4]
@willtcarey thoughts on this?

> Trying to break the habit of running `bundle exec` instead of Rails `bin/` stubs (they're faster!)

https://twitter.com/searls/status/1359520501077602312

**Comment by willtcarey** [comment]
I saw this over the weekend and I made a mental note to check into it. I have no idea why they would be faster unless they're not loading all bundled gems when you use the binstubs?

**Comment by willtcarey** [comment]
Results from Merchtable
```
bash-5.0# time bin/rails runner "puts \"hello\""
hello

real    0m1.701s
user    0m1.506s
sys     0m0.200s
```

```
bash-5.0# time bundle exec rails runner "puts \"hello\""
hello

real    0m2.033s
user    0m1.734s
sys     0m0.303s
```

I suppose we have incontrovertible proof that the binstubs are faster?
