### ISSUE TITLE
Command to Restart Services

### ISSUE THREAD

**Issue by nathancolgate** [brandnewbox/bnb-dip-defaults#6]
I used to run `docker-compose restart app` to reboot just the puma server or something.

But now that framer moves the docker compose file into a subdirectory, I'd have to pass that config file to my command.

What I would love: `dip restart app`.

Just noodling.

**Comment by willtcarey** [comment]
`dip compose restart app` is the equivalent thing

**Comment by nathancolgate** [comment]
Close enough!
